---
title: "Raspored"
---

<br>
<br>

<br>
<br>
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/01_UVOD_XAR.html">Predavanje 01: Pregled kolegija i studentskih obveza</a>
<br>
<br>

<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/03_VRSTEdtaXAR.html">Predavanje 02: Vrste podataka</a>
<ul>
<li> Strukturirani i ne-strukturirani podatci</li>
<li> <a href="https://www.youtube.com/watch?v=_I2GrxUGNQc&t=2">Kvantitativni i kvalitativni</a></li>
<li> Diskretni i kontinuirani podatci</li>
<li> Razine podataka</li>
<li> Podatci u "praksi"</li>
<li> <a href="/Literatura/Shu-Heng Chen - Big Data in Computational Social Science and Humanities-Springer (2018).pdf">"Big data" u društvenim i humanističkim znanostim</a></li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/03_VRSTEdtaXAR.html">.html</a> | <a href="/Predavanja/03_VRSTEdtaXAR.Rmd">.Rmd</a> 
<br><b>Čitanje: </b><a href="/Literatura/Vrste_podataka.pdf">Vrste podataka-poglavlje u knjizi</a> + <a href="/Literatura/Sociology in the Era of Big Data.pdf">Sociology in the Era of Big Data</a> + <a href="/Literatura/VELIKI PODACI – VELIKI IZAZOV ZA SOCIOLOGIJU.pdf">Veliki podatci-veliki izazov za sociologiju</a> + <a href="/Literatura/Msc_mastruko_Kristalna kugla.pdf">Uloga big data, algoritama i prediktivne analitike u konstrukciji zbilje</a>
<br>
<br>

<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/03_IZVORIdtaXAR.html">Predavanje 03: Izvori podataka</a>
<ul>
<li> Kategorije izvora podatka</li>
<li> Klasični izvori podataka</li>
<li> Moderni izvori podataka (BigData)</li>
<li> Web</li>
<li> Društvene mreže</li>
<li> Web stranice i aplikacije</li>
<li> Društvene mreže</li>
<li> Senzori</li>
<li> Upravljanje modernim podatcima</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/03_IZVORIdtaXAR.html">.html</a> | <a href="/Predavanja/03_IZVORIdtaXAR.Rmd">.Rmd</a> 
<br><b>Čitanje: </b><a href="/Literatura/BDSources.pdf">Big Data ekosistem u društvenim istraživanjima</a>
<br>
<br>


<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/04_OSNOVE_R.html">Predavanje 04: Osnove programskog jezika R</a> + <a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/04_OSNOVE_R_ggplot2.html"> Dodatak predavanju: ggplot2</a>
<ul>
<li> Instalacija</li>
<li> Zašto R?</li>
<li> Osnovni koncepti</li>
<li> Objektno orjentirano programiranje u R</li>
<li> "Sve je objekt"</li>
<li> "Sve ima naziv"</li>
<li> Indeksiranje</li>
<li> Čišćenje radnog prostora</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/04_OSNOVE_R.html">.html</a> | <a href="/Predavanja/04_OSNOVE_R.Rmd">.Rmd</a> + <a href="/Predavanja/04_OSNOVE_R_ggplot2.html">.html (ggplot2)</a> | <a href="/Predavanja/04_OSNOVE_R_ggplot2.Rmd">.Rmd (ggplot2)</a>
<br><b>Čitanje: </b><a href="https://www.srce.unizg.hr/files/srce/docs/edu/R/s720_polaznik.pdf">Uvod u R - skripta I</a> + </b><a href="https://cran.r-project.org/doc/contrib/Kasum+Legovic-UvodUr.pdf">Uvod u R - skripta II</a> + </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR, poglavlja 3 i 4</a>
<br>
<br>

<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/05_MANIPULACIJA_tidy.html">Predavanje 05: Manipulacija i prilagodba podataka</a> + <a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/05_MANIPULACIJA_dt.html"> Dodatak predavanju: data.table</a>
<ul>
<li> Set-up</li>
<li> tidyverse osnove</li>
<li> Manipulacija podatcima - dplyr</li>
<li> Manipulacija podatcima - tidyr</li>
<li> + Dodatak predavanju: data.table</li>
<ul>

</div>


<b>Format predavanja:</b> <a href="/Predavanja/05_MANIPULACIJA_tidy.html">.html</a> | <a href="/Predavanja/05_MANIPULACIJA_tidy.Rmd">.Rmd</a> + <a href="/Predavanja/05_MANIPULACIJA_dt.html">.html (data.table)</a> | <a href="/Predavanja/05_MANIPULACIJA_dt.Rmd">.Rmd (data.table)</a>
<br><b>Čitanje: </b><a href="https://vita.had.co.nz/papers/tidy-data.pdf">Tidy Data članak od Hadley Wickham-a</a>
<br>
<br>

<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/06_WEBSCRAP.html">Predavanje 06: Prikupljanje podataka sa interneta - Web Scraping I</a>  + <a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/06_WEBSCRAP_I.html">Web Scraping II</a>


<ul>
<li> Softverski set-up</li>
<li> Webscraping osnove</li>
<li> WS na strani servera - rvest</li>
<li> Praktični primjeri - Wikipedia</li>
<li> Dodatni savjeti za WS na strani servera</li>
<li> WS na strani klijenta</li>
<li> API</li>
<li> Praktični primjeri (I,II ,III)</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/06_WEBSCRAP.html">.html (WebScrap I)</a> | <a href="/Predavanja/06_WEBSCRAP.Rmd">.Rmd (WebScrap I)</a> + <a href="/Predavanja/06_WEBSCRAP_I.html">.html (WebScrap II)</a> | <a href="/Predavanja/06_WEBSCRAP_I.Rmd">.Rmd ((WebScrap II)</a>
<br><b>Čitanje: </b><a href="">Pokušajte "scrapati" nešto sa Web-a!</a>
<br>
<br>




<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/07_BAZE.html">Predavanje 07: Rad sa bazama podataka</a>

<ul>
<li> Baze podatka</li>
<li> Baze podataka i *tidyverse*</li>
<li> Baze podataka i SQL</li>
<li> Praktični primjer - SQLite</li>
<li> Praktični primjer - Google BigQuery</li>
<li> Resursi za učenje</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/07_BAZE.html">.html</a> | <a href="/Predavanja/07_BAZE.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://wizardzines.com/zines/sql/">Knjiga *Become A Select Star* od Julia-e Evans.</a>
<br>
<br>


<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/08_STATS.html">Predavanje 08: Statistička analiza</a>

<ul>
<li> Regresijski model</li>
<li> Rezidualna struktura</li>
<li> Dummie varijable</li>
<li> Analiza panel podataka</li>
<li> Instrumentalne varijable</li>
<li> Marginalni efekti</li>
<li> Prezentacija rezultata</li>
<li> Dodatni resursi</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/08_STATS.html">.html</a> | <a href="/Predavanja/08_STATS.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="">Izbor po želji iz dodatnih resursa.</a>
<br>
<br>


<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/09_ML.html">Predavanje 09: Uvod u strojno učenje</a>

<ul>
<li> Što je strojno učenje</li>
<li> Klasifikacija</li>
<li> Regresija</li>
<li> Klastering</li>
<li> Nadgledane i ne-nadgledane metode</li>
<li> Trening i test uzorci</li>
<li> Pristranost vs varijanca</li>
<li> Interpretabilnost modela</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/09_ML.html">.html</a> | <a href="/Predavanja/09_ML.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="">Izbor po želji iz dodatnih resursa.</a>
<br>
<br>

<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/10_TXT.html">Predavanje 10: Analiza teksta</a>

<ul>
<li> Što je analiza teksta</li>
<li> Primjeri analize teksta</li>
<li> Uvoz i priprema teksta (preprocesing korpusa)</li>
<li> Format teksta za analizu (TidyText vs DTM)</li>
<li> Deskriptivna analiza teksta (frekvencije riječi)</li>
<li> Analiza sentimenta</li>
<li> Analiza važnosti pojmova</li>
<li> Tematska analiza</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/10_TXT.html">.html</a> | <a href="/Predavanja/10_TXT.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="http://eprints.lse.ac.uk/86659/1/Benoit_Text%20analysis%20in%20R_2018.pdf">Vodič za analizu teksta u R</a>
<br>
<br>



<div style="width: 25%; margin-left: auto; margin-right: auto;">
<a href="https://raw.githack.com/BrbanMiro/Obrada-podataka/main/Predavanja/11_RMD.html">Predavanje 11: Prezentacija, objava i djeljenje rezultata</a>

<ul>
<li> Reproducible research i Markdown</li>
<li> Markdown sintaksa</li>
<li> R Markdown sintaksa i funkcionalnosti</li>
<ul>

</div>

<b>Format predavanja:</b> <a href="/Predavanja/11_RMD.html">.html</a> | <a href="/Predavanja/10_RMD.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://dukespace.lib.duke.edu/dspace/bitstream/handle/10161/8374/Baumer_R%20Markdown-Integrating%20a%20Reproducible%20Analysis%20Tool%20into%20Introductory%20Statistics.pdf?sequence=1"> Članak o Reproducible Analysis</a>
<br>
<br>

<br>
<br>
<br>


